### PR TITLE
Front End: Round values in frontend #112

### PR DESCRIPTION
**Pull request by fabiancdng**
Round values on the front end side with a fixed amount of decimal digits
using `Number.prototype.toFixed()`. Also adds unit to the weight delta
string.

Resolves Round values in frontend #112

### CODE REVIEW

**Comment by fabiancdng** [comment]
Screenshot 2022-05-05 at 18 52 23

**Comment by AuxiliumCDNG** [comment]
Let's rename this branch to "rounded-values" or something like this and merge the pr into "frontend-improvements" ok?

**Comment by fabiancdng** [comment]
@AuxiliumCDNG Merged into `frontend-improvements`. We'll continue work from there.

**Comment by AuxiliumCDNG** [comment]
@fabiancdng Save to delete?

**Pull request closed without merging**
