### PR TITLE
Front End: Now saving settings in local storage

### LINKED ISSUE #56: Use localStorage to save the state of the 'seperate weight' switch
Currently the 'seperate weight' switch for the compare chart flips back to 'off' as soon as you reload the page or update the charts.

My idea is to save the last state of this switch in the user's localStorage. So if the user enables the option, it doesn't get disabled on page reload or chart re-draw.

Screenshot 2021-09-18 at 09 58 51

### PR DESCRIPTION
**Pull request by AuxiliumCDNG**
Closes #56 
Please run some thorough testing. I have no idea if it works reliably tbh. xD

### CODE REVIEW

**Comment by fabiancdng** [comment]
I ran into some issues with the separate scale switch + I added some logic to unset the items in localStorage (other than `daterange-save-to`) when the user disabled the feature. Hope my changes are fine with you. Other than that, very well done, great feature!

**Comment by AuxiliumCDNG** [comment]
You use firefox, right?
Why you read an unset item, does it return null as in not set or "null" as a string?
Chromium seems to do the latter. Is that the/a problem? Cause it worked for me obviously...
That's why the if clauses are a bit weird in my version...

**Comment by fabiancdng** [comment]
@AuxiliumCDNG Oh, that's interesting... Both Chrome and Firefox (on macOS) return `null` (the type) if the item is not set, not a string. But considering it seems to be a string for you, we might want to switch to `localStorage.hasOwnProperty('key')` for checking whether the item is set in the storage. This should (in every browser) result in either `true` or `false` being returned.... I love JavaScript :)

**Comment by AuxiliumCDNG** [comment]
What about other datatypes? Are booleans still booleans when you read them? They get "converted" to strings in my browser (Vivaldi). Thats why bools are supposed to be 0/1 (which is also a string 😂).
I will run some tests this evening and commit a fix (hopefully). Oh dear...

**Comment by AuxiliumCDNG** [comment]
> Hope my changes are fine with you.

Your changes break the intended use of daterange-save-to which is to keep the "end-date" up to date but keep all other settings. "to" not "too".
That's handy when you load the site days later to see current data. It shouldn't delete all settings.

Have a look at https://github.com/Programmier-AG/BeeLogger/wiki/Miscellaneous#localstorage-keys

**Comment by AuxiliumCDNG** [comment]
I would actually like to roll back and fix what's wrong in place. Or if you want to fix your version, you can do that. Your decision.

**Comment by fabiancdng** [comment]
@AuxiliumCDNG Reverted my changes, the branch is now back to where you left off.

**Comment by AuxiliumCDNG** [comment]
I will try to come up with a fix. The same browser on windows 11 instead of 10 behaves as your browsers do btw. I will try to make it as redundant and "javascript-save" as possible.

**Comment by fabiancdng** [comment]
@AuxiliumCDNG I don't know if this helps but `JSON.parse("null");` and `JSON.parse(null);` should both result in `null` (the type; not string). Maybe you can use that to fix the issue.

**Comment by AuxiliumCDNG** [comment]
Please hang on while I test the merge...

**Comment by AuxiliumCDNG** [comment]
@fabiancdng Please verify everything is working. Then feel free to merge.
Should be safe to delete...

**Comment by fabiancdng** [comment]
@AuxiliumCDNG It works for me. Only the checkbox to opt-in or out of saving the settings in the `localStorage` does nothing (at least in my browser) 😕 If I uncheck it, the values are still being stored and read from the localStorage.

Screenshot 2022-05-08 at 00 32 05

**Comment by AuxiliumCDNG** [comment]
Uncheck it, change end date to yesterday, apply, reload the page and check if the end date changes. Does it change?

**Comment by AuxiliumCDNG** [comment]
Works for me now in Vivaldi 5.2.2623.41 (Stable channel) (64-Bit), which is the current build.
Also tested in Chrome Version 101.0.4951.54 (Offizieller Build) (64-Bit)
and Firefox 100.0 (64-Bit).

**Review by fabiancdng — APPROVED** [review]
@AuxiliumCDNG Okay for me to merge then, thanks! It worked for me too except for the checkbox weirdness... But maybe that was just Firefox caching input states across tabs or me being dumb, who knows

**Comment by AuxiliumCDNG** [comment]
> Uncheck it, change end date to yesterday, apply, reload the page and check if the end date changes. Does it change?

@fabiancdng Did you do that?

**Comment by fabiancdng** [comment]
@AuxiliumCDNG Tried that both with the start and end date. It didn't change back when the checkbox was unchecked. Only tested it with Firefox though

**Comment by AuxiliumCDNG** [comment]
@fabiancdng Could you run `localStorage.clear()` and try again?

**Comment by fabiancdng** [comment]
@AuxiliumCDNG Oh haha works now 😅 Is it intentional that only the end date resets and not the start date?

**Comment by AuxiliumCDNG** [comment]
> > Hope my changes are fine with you.
> 
> Your changes break the intended use of daterange-save-to which is to keep the "end-date" up to date but keep all other settings. "to" not "too". That's handy when you load the site days later to see current data. It shouldn't delete all settings.
> 
> Have a look at https://github.com/Programmier-AG/BeeLogger/wiki/Miscellaneous#localstorage-keys

@fabiancdng It is

**Comment by fabiancdng** [comment]
@AuxiliumCDNG Sorry, overlooked that. I understand.

**Pull request merged**
